apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cpu-thingy
  name: cpu-thingy
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cpu-thingy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cpu-thingy
    spec:
      containers:
      - args:
        - 500000 20000000 2000000
        image: diversario/interesting-graphs:latest
        imagePullPolicy: Always
        name: interesting-graphs
        resources:
          limits:
            cpu: 1
            memory: 4Gi
        volumeMounts:
        - mountPath: /tmp
          name: host-dir
      volumes:
      - name: host-dir
        hostPath:
          path: /tmp
          type: Directory